### ISSUE TITLE
Package editor quits if 3d model path is invalid/missing

### ISSUE THREAD

**Issue by frmdstryr** [horizon-eda/horizon#414]
The [3d model for the NX3225SA](https://github.com/horizon-eda/horizon-pool/blob/master/packages/manufacturer/ndk/4smd-3.2x2.5mm/package.json#L262) is not in the pool `3d_models/local/crystal/NX3225SA v2.step`.  

When I try to open the package 3d editor to change the path the editor quits with exit code 6.

**Comment by frmdstryr** [comment]
```c
#0  0x00007fffeffabe97 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fffeffad801 in __GI_abort () at abort.c:79
#2  0x00007ffff0610257 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff061b606 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff061b671 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff061b905 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff3bff1e7 in Gio::Error::throw_func(_GError*) () at /usr/lib/x86_64-linux-gnu/libgiomm-2.4.so.1
#7  0x00007ffff36b0831 in Glib::Error::throw_exception(_GError*) () at /usr/lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#8  0x00007ffff3c00264 in Gio::File::query_info(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Gio::FileQueryInfoFlags) const () at /usr/lib/x86_64-linux-gnu/libgiomm-2.4.so.1
#9  0x0000555555e67b85 in operator()<std::pair<const std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > > (__closure=<synthetic pointer>, x={...}) at /usr/include/c++/10/bits/char_traits.h:322
#10 0x0000555555e67b85 in std::transform<std::_Rb_tree_iterator<std::pair<const std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > >, std::back_insert_iterator<std::vector<horizon::Canvas3D::load_models_thread(std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >)::FilenameItem> >, horizon::Canvas3D::load_models_thread(std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >)::<lambda(const auto:9&)> >Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer': 
 (__unary_op=..., __result=..., __last=..., __first=...) at /usr/include/c++/10/bits/stl_algo.h:4313
#11 0x0000555555e67b85 in horizon::Canvas3D::load_models_thread(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >) (this=0x555557035d00, model_filenames=...) at src/canvas3d/canvas3d.cpp:329
#12 0x0000555555e6b582 in std::__invoke_impl<void, void (horizon::Canvas3D::*)(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >), horizon::Canvas3D*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >(std::__invoke_memfun_deref, void (horizon::Canvas3D::*&&)(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >), horizon::Canvas3D*&&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&&) (__t=<optimized out>, __f=<optimized out>) at /usr/include/c++/10/bits/stl_tree.h:211
#13 0x0000555555e6b582 in std::__invoke<void (horizon::Canvas3D::*)(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >), horizon::Canvas3D*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >(void (horizon::Canvas3D::*&&)(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >), horizon::Canvas3D*&&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&&) (__fn=<optimized out>) at /usr/include/c++/10/bits/invoke.h:95
#14 0x0000555555e6b582 in std::thread::_Invoker<std::tuple<void (horizon::Canvas3D::*)(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >), horizon::Canvas3D*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::_M_invoke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>) (this=<optimized out>) at /usr/include/c++/10/thread:264
#15 0x0000555555e6b582 in std::thread::_Invoker<std::tuple<void (horizon::Canvas3D::*)(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >), horizon::Canvas3D*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > >::operator()() (this=<optimized out>) at /usr/include/c++/10/thread:271
#16 0x0000555555e6b582 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (horizon::Canvas3D::*)(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >), horizon::Canvas3D*, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > > >::_M_run() (this=<optimized out>) at /usr/include/c++/10/thread:215
#17 0x00007ffff0646d80 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#18 0x00007ffff7bbd6db in start_thread (arg=0x7fffc29d4700) at pthread_create.c:463
#19 0x00007ffff008e88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95



```

**Comment by frmdstryr** [comment]
Thanks!
